# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'CAP Days 2024'
tagline:          'CAP Days'
description:      'Workshop July 1-5, 2024'
location:         'Université de Picardie Jules Verne, Amiens, France'
url:              https://homalg-project.github.io
baseurl:          /capdays-2024


exclude: [ "LICENSE.hyde.md", "README.hyde.md" ]
include: [ ]
